// lib/data/predict_data.dart
final Map<String, int> initialFormData = {
  'TALLA/EDAD (ACTUAL)_0': 0,
  'TALLA/EDAD (ACTUAL)_Alto': 0,
  'TALLA/EDAD (ACTUAL)_Bajo': 0,
  'TALLA/EDAD (ACTUAL)_Normal': 0,
  'Peso al nacer/edad gestacional_0': 0,
  'Peso al nacer/edad gestacional_Adecuado': 0,
  'Peso al nacer/edad gestacional_Alto': 0,
  'Peso al nacer/edad gestacional_Bajo': 0,
  'SEXO': 0,
  'PESO': 0,
  'EDAD': 0,
  'BAJO PESO AL NACER': 0,
  'TALLA/EDAD (ACTUAL).1': 0,
  'PESO/EDAD (ACTUAL)': 0,
  'RDPM / DISCAPACIDAD INTELECTUAL': 0,
  'CARACTERISTICAS FACIALES': 0,
  'DEPRESION BITEMPORAL': 0,
  'CEJAS ARQUEADAS': 0,
  'PLIEGUE EPICANTICO': 0,
  'PATRON ESTELAR DEL IRIS': 0,
  'PUENTE NASAL DEPRIMIDO': 0,
  'NARIZ CORTA NARINAS ANTEVERTIDAS': 0,
  'PUNTA NASAL ANCHA O BULBOSA': 0,
  'MEJILLAS PROMINENTES': 0,
  'REGION MALAR PLANA': 0,
  'FILTRUM LARGO': 0,
  'LABIOS GRUESOS': 0,
  'DIENTES PEQUEÑOS O ESPACIADOS': 0,
  'PALADAR ALTO Y OJIVAL': 0,
  'BOCA AMPLIA': 0,
  'PABELLONES AURICULARES GRANDES': 0,
  'CARDIOPATIA CONGENITA': 0,
  'ESTENOSIS SUPRAVALVULAR AORTICA': 0,
  'ESTENOSIS PULMONAR': 0,
  'OTRA CARDIOPATIA': 0,
  'OTRAS ALTERACIONES': 0,
  'VOZ DISFONICA': 0,
  'TRASTORNO TIROIDEO': 0,
  'TRASTORNO DE LA REFRACCION': 0,
  'HERNIA': 0,
  'ORQUIDOPEXIA': 0,
  'SINOSTOSIS RADIOCUBITAL': 0,
  'HIPERLAXITUD ARTICULAR': 0,
  'ANTECEDENTE DE ORQUIDOPEXIA': 0,
  'ESCOLIOSIS': 0,
  'HIPERCALCEMIA': 0,
  'RETRASO EN EL DESARROLLO PSICOMOTOR': 0,
  'DÉFICIT COGNITIVO': 0,
  'PERSONALIDAD SOCIAL EXTREMA': 0,
  'TRASTORNOS DEL APRENDIZAJE': 0,
  'ANSIEDAD O FOBIAS (Sonidos fuertes, lugares cerrados, separación, etc.)': 0,
  'PROBLEMAS DEL SUEÑO (Insomnio, despertares nocturnos)': 0,
  'GENÉTICA CONFIRMADA (Deleción 7q11.23 / Sin análisis)': 0,
  'ESTUDIO MOLECULAR CONFIRMATORIO': 0,
  'HIPOACUSIA': 0,
  'HIPERSENSIBILIDAD AUDITIVA (HIPERACUSIA)': 0,
  'ALTERACIONES VISUALES (Miopía, astigmatismo, estrabismo)': 0,
  'ALTERACIONES HORMONALES (Pubertad tardía, alteraciones tiroideas adicionales)': 0,
  'DIABETES INFANTIL O INTOLERANCIA A LA GLUCOSA': 0,
  'DÉFICIT DE CRECIMIENTO': 0,
};

final List<Map<String, String>> campos = initialFormData.keys
    .map((k) => {'label': k.contains("ANSIEDAD") ? "ANSIEDAD O FOBIAS" : (k.contains("PROBLEMAS DEL SUEÑO") ? "PROBLEMAS DEL SUEÑO" : (k.contains("GENÉTICA CONFIRMADA") ? "GENÉTICA CONFIRMADA" : k)), 'key': k})
    .toList();

final Map<String, String> infoTexts = {
  'TALLA/EDAD (ACTUAL)_0': 'Evaluar la proporción entre la talla y la edad del paciente. Valorar desviaciones significativas.',
  'Peso al nacer/edad gestacional_0': 'Importancia de evaluar el peso al nacer para identificar posibles riesgos tempranos.',
  'SEXO': 'Seleccione el sexo del paciente, ya que ciertas características pueden variar.',
  'CARACTERISTICAS FACIALES': 'Observar y registrar características faciales distintivas del síndrome de Williams.',
  'DÉFICIT COGNITIVO': 'Evaluar posibles déficits cognitivos asociados con el síndrome.',
  'TALLA/EDAD (ACTUAL)_Alto': 'Indica una estatura superior a la media para la edad del paciente.',
  'TALLA/EDAD (ACTUAL)_Bajo': 'Indica una estatura inferior a la media para la edad del paciente.',
  'TALLA/EDAD (ACTUAL)_Normal': 'Estatura dentro del rango normal para la edad del paciente.',
  'Peso al nacer/edad gestacional_Adecuado': 'Peso al nacer proporcional a la edad gestacional.',
  'Peso al nacer/edad gestacional_Alto': 'Peso al nacer superior al promedio para la edad gestacional.',
  'Peso al nacer/edad gestacional_Bajo': 'Peso al nacer inferior al promedio para la edad gestacional.',
  'PESO': 'Registrar el peso actual del paciente.',
  'EDAD': 'Registrar la edad actual del paciente.',
  'BAJO PESO AL NACER': 'Indicar si el paciente tuvo un peso bajo al nacer.',
  'TALLA/EDAD (ACTUAL).1': 'Información adicional sobre la talla en relación con la edad.',
  'PESO/EDAD (ACTUAL)': 'Evaluar el peso en relación con la edad actual del paciente.',
  'RDPM / DISCAPACIDAD INTELECTUAL': 'Revisar retraso en el desarrollo psicomotor y/o presencia de discapacidad intelectual.',
  'DEPRESION BITEMPORAL': 'Verificar si hay depresión en las sienes, un signo físico posible.',
  'CEJAS ARQUEADAS': 'Identificar si las cejas presentan una forma arqueada distintiva.',
  'PLIEGUE EPICANTICO': 'Presencia de pliegues en la esquina interna de los ojos.',
  'PATRON ESTELAR DEL IRIS': 'Buscar patrones inusuales en el iris del ojo.',
  'PUENTE NASAL DEPRIMIDO': 'Observar si el puente nasal es más bajo de lo normal.',
  'NARIZ CORTA NARINAS ANTEVERTIDAS': 'Nariz visualmente corta con narinas que apuntan hacia adelante.',
  'PUNTA NASAL ANCHA O BULBOSA': 'Nariz con punta ancha o bulbosa.',
  'MEJILLAS PROMINENTES': 'Cheques visiblemente destacadas.',
  'REGION MALAR PLANA': 'Plano en la región de los pómulos.',
  'FILTRUM LARGO': 'Distancia inusualmente larga entre la nariz y el labio superior.',
  'LABIOS GRUESOS': 'Labios más gruesos de lo habitual.',
  'DIENTES PEQUEÑOS O ESPACIADOS': 'Dientes anormalmente pequeños o con espacios entre ellos.',
  'PALADAR ALTO Y OJIVAL': 'Paladar inusualmente alto y en forma de arco.',
  'BOCA AMPLIA': 'Anomalía caracterizada por una boca más ancha de lo normal.',
  'PABELLONES AURICULARES GRANDES': 'Orejas más grandes de lo normal.',
  'CARDIOPATIA CONGENITA': 'Presencia de una condición cardíaca presente desde el nacimiento.',
  'ESTENOSIS SUPRAVALVULAR AORTICA': 'Estrechamiento de la válvula aórtica del corazón.',
  'ESTENOSIS PULMONAR': 'Estrechamiento de la válvula pulmonar que afecta el flujo sanguíneo al pulmón.',
  'VOZ DISFONICA': 'Anomalías en el tono o la calidad de la voz.',
  'TRASTORNO TIROIDEO': 'Problemas relacionados con la glándula tiroides.',
  'HIPOACUSIA': 'Reducción en la capacidad auditiva.',
  'HIPERSENSIBILIDAD AUDITIVA (HIPERACUSIA)': 'Sensibilidad excesiva a los sonidos.',
  'OTRA CARDIOPATIA': 'Cualquier otra anomalía cardíaca no especificada previamente.',
  'OTRAS ALTERACIONES': 'Anomalías no clasificadas en otros ítems, de tipo clínico o morfológico.',
  'HERNIA': 'Presencia de una protrusión de un órgano a través de una abertura anormal.',
  'ORQUIDOPEXIA': 'Cirugía realizada para descender testículos que no se encuentran en el escroto.',
  'SINOSTOSIS RADIOCUBITAL': 'Fusión anormal entre los huesos del radio y cúbito del antebrazo.',
  'HIPERLAXITUD ARTICULAR': 'Flexibilidad articular excesiva más allá del rango normal.',
  'ANTECEDENTE DE ORQUIDOPEXIA': 'Indica si el paciente ya fue sometido a orquidopexia previamente.',
  'ESCOLIOSIS': 'Desviación lateral anormal de la columna vertebral.',
  'HIPERCALCEMIA': 'Elevación anormal de los niveles de calcio en la sangre.',
  'RETRASO EN EL DESARROLLO PSICOMOTOR': 'Demora en alcanzar hitos motores y cognitivos esperados para la edad.',
  'PERSONALIDAD SOCIAL EXTREMA': 'Tendencia a comportamientos sociales muy marcados, como hiperafiliación.',
  'TRASTORNOS DEL APRENDIZAJE': 'Dificultades significativas en habilidades escolares básicas como lectura o cálculo.',
  'ANSIEDAD O FOBIAS (Sonidos fuertes, lugares cerrados, separación, etc.)': 'Presencia de miedos marcados o ansiedad frente a estímulos comunes.',
  'PROBLEMAS DEL SUEÑO (Insomnio, despertares nocturnos)': 'Dificultades para iniciar o mantener el sueño adecuadamente.',
  'GENÉTICA CONFIRMADA (Deleción 7q11.23 / Sin análisis)': 'Confirmación o sospecha de deleción cromosómica asociada al síndrome de Williams.',
  'ESTUDIO MOLECULAR CONFIRMATORIO': 'Prueba molecular que avala el diagnóstico genético.',
  'ALTERACIONES VISUALES (Miopía, astigmatismo, estrabismo)': 'Trastornos oculares que afectan la visión normal del paciente.',
  'ALTERACIONES HORMONALES (Pubertad tardía, alteraciones tiroideas adicionales)': 'Trastornos endocrinos como disfunción tiroidea o alteración del desarrollo puberal.',
  'DIABETES INFANTIL O INTOLERANCIA A LA GLUCOSA': 'Desregulación del metabolismo de la glucosa en la infancia.',
  'DÉFICIT DE CRECIMIENTO': 'Crecimiento físico por debajo del percentil esperado para la edad y sexo.',

};
